### PR TITLE
Atom: Update raw package-list.txt plugin versions

### PR DESCRIPTION
**Pull request by pzrq**
e.g. `fileicons@1.6.9` no longer installs and prints in red text `Package version: 1.6.9 not found`, so it has been bumped to `1.7.19`

---

This change is [Reviewable](https://reviewable.io/reviews/mongodb-js/mongodb-js/4)

### CODE REVIEW

**Comment by pzrq** [comment]
@rueckstiess Do you tend to update Atom `apm` packages to the latest versions of everything or stick with known good versions? I can update this PR with latest versions if you think it's a good idea.

**Comment by rueckstiess** [comment]
Update to latest version makes total sense. Probably lots of bug fixes since then :-)

**Comment by pzrq** [comment]
@rueckstiess Updated with my output of `apm list --installed --bare`, thanks.

**Comment by kangas** [comment]
@rueckstiess Does it make sense to specify a list of specific package versions? It seems like this will get stale quickly, again.

Should recommendation to new team members be to install the latest for each of these packages at any given time?

**Comment by pzrq** [comment]
@kangas @rueckstiess I agree there's little value in pinning to specific plugin versions, I have updated the suggested `packages-list.txt` to drop the specific versions.

**Review by rueckstiess — APPROVED** [review]
Thanks, yes not pinning the version numbers makes much more sense. That was just the way `apm` created the file.

LGTM

**Comment by pzrq** [comment]
Thanks @kangas @rueckstiess 👍

**Pull request merged**
